language: minimal
# because we edit /etc/hosts
sudo: required
# gives us a prefix function to handle no-output situations up to X minutes
# install: travis_wait 40 mvn install

branches:
  only:
  - travis
  - travis-1-1-1-release

git:
  submodules: false

notifications:
  email: false

services:
  - docker

addons:
  chrome: stable

before_install:
  - git clone https://github.com/Born-Digital-US/isle-ingest-samples.git
  - mv docker-compose.yml docker-compose.yml.default
  - cp isle-ingest-samples/docker-compose.yml docker-compose.yml
  - docker-compose pull
  - docker-compose up -d
  - sleep 40
  - set -x && docker exec -it isle-apache-ld bash /utility-scripts/isle_drupal_build_tools/isle_islandora_installer.sh
  - docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_batch"
  - docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/all/modules/islandora && git clone https://github.com/mjordan/islandora_batch_with_derivs.git"
  - docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_batch_with_derivs"
  - docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_book_batch"
  - docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_newspaper_batch"
  - docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/all/modules/islandora && git clone https://github.com/MarcusBarnes/islandora_compound_batch.git"
  - docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_compound_batch"
  - docker cp isle-ingest-samples isle-apache-ld:/var/www/html/bd-samples
  - sudo -- sh -c "echo 127.0.0.1 isle.localdomain >> /etc/hosts"
  # full ingest
  - travis_wait 60 docker exec -it isle-apache-ld bash -c "sh /var/www/html/bd-samples/Batches-by-CModel/ingest_samples.sh /var/www/html"
  # - docker exec -it isle-apache-ld bash -c "sh /var/www/html/bd-samples/Batches-by-CModel/ingest_samples.sh /var/www/html"
  # partial ingest
  # - docker exec -it isle-apache-ld bash -c "head -n40 /var/www/html/bd-samples/Batches-by-CModel/ingest_samples.sh > /var/www/html/bd-samples/Batches-by-CModel/ingest_samples_brief.sh && sh /var/www/html/bd-samples/Batches-by-CModel/ingest_samples_brief.sh /var/www/html"
  - docker exec -it isle-apache-ld bash -c "mv /var/www/html/bd-samples/behat /var/www/html/sites/."
  - docker exec -it isle-apache-ld bash -c "composer global require drush/drush:7.*"
  - docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/behat && rm composer.lock && composer install "
  # - docker exec -it isle-apache-ld bash -c "mkdir /tmp/artifacts"

script:
  - docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/behat && php behat --profile=travis --verbose"
