language: minimal

branches:
  only:
  - travis

git:
  submodules: false

notifications:
  email: false

services:
  - docker

before_install:
  - git clone https://github.com/Born-Digital-US/isle-ingest-samples.git
  - docker-compose pull
  - docker-compose up -d
  - sleep 40
  - set -x && docker exec -it isle-apache-ld bash /utility-scripts/isle_drupal_build_tools/isle_islandora_installer.sh

script:
  - docker ps -a
