version: '3'

#### docker-compose up -d;
## Updated 2019-03-27 - Release TICK (@ dashboards-dev)

services:
  isle-portainer: ## Renamed to avoid conflicts on systems/servers with portainer already running.
    image: portainer/portainer
    container_name: isle-portainer-${CONTAINER_SHORT_ID}
    command: -H unix:///var/run/docker.sock --no-auth
    networks:
      - isle-internal
    ports:
      - "9010:9000" ## Remapped to avoid conflicts on systems/servers with portainer already running.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - isle-portainer-data:/data
    labels:
      - traefik.port=9000
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      - traefik.enable=true  ## NOT SAFE FOR PRODUCTION! ##
      - "traefik.frontend.rule=Host:portainer.${BASE_DOMAIN};"

  mysql:
    # build:
    #   context: ../images/isle-mysql
    image: islandoracollabgroup/isle-mysql:dashboards-dev
    container_name: isle-mysql-${CONTAINER_SHORT_ID}
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - isle-internal
    ports:
      - "3306:3306"      
    volumes:
      - isle-db-data:/var/lib/mysql
      - isle-mysql-log:/var/log/mysql


  fedora:
    # build:
    #   context: ../images/isle-fedora
    image: islandoracollabgroup/isle-fedora:dashboards-dev    
    container_name: isle-fedora-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=768M
      - JAVA_MIN_MEM=128M
    env_file: 
      - tomcat.env
      - .env
    networks:
      - isle-internal
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - solr
    volumes:
      - isle-fedora-datastreamStore:/usr/local/fedora/data/datastreamStore # Migrators change this to your local DS folder.
      - isle-fedora-objectStore:/usr/local/fedora/data/objectStore # Migrators change this to your local OS folder.
      - isle-fedora-resourceIndex:/usr/local/fedora/data/resourceIndex # Migrators change this to your local RI folder.
      - isle-fedora-activemq:/usr/local/fedora/data/activemq-data # Migrators change this to your local MQ folder.
      - isle-fedora-XACML:/usr/local/fedora/data/fedora-xacml-policies


  solr:
    # build:
    #   context: ../images/isle-solr
    image: islandoracollabgroup/isle-solr:dashboards-dev
    container_name: isle-solr-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=512M
      - JAVA_MIN_MEM=0
    env_file: 
      - tomcat.env
      - .env
    networks:
      - isle-internal
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    volumes:
      - isle-solr-data:/usr/local/solr  


  image-services:
    # build:
    #   context: ../images/isle-imageservices
    image: islandoracollabgroup/isle-imageservices:dashboards-dev
    container_name: isle-images-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=512M
      - JAVA_MIN_MEM=0
    env_file: 
      - tomcat.env
      - .env
    networks:
      - isle-internal
    depends_on:
      - apache
      - fedora
    ports:
      - "8083:8080"
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      - traefik.enable=false
      - "traefik.frontend.rule=Host:images.${BASE_DOMAIN}; PathPrefix: /, /adore-djatoka, /cantaloupe"


  apache:
    # build:
    #   context: ../images/isle-apache
    image: islandoracollabgroup/isle-apache:dashboards-dev
    container_name: isle-apache-${CONTAINER_SHORT_ID}
    env_file: 
      - .env
    networks:
      isle-internal:
    depends_on:
      - mysql
      - fedora
      - solr
      - traefik
    volumes:
      - isle-apache-data:/var/www/html
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      - traefik.enable=true
      - "traefik.frontend.rule=Host:${BASE_DOMAIN}; PathPrefix: /, /adore-djatoka, /cantaloupe"

# Start TICK - Services

  influxdb:
    image: influxdb:latest
    container_name: isle-influxdb-${CONTAINER_SHORT_ID}
    volumes:
      # Mount for influxdb data directory
      - isle-influxdb-data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./config/tick/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8088:8088"
      # UDP Port
      - "8089:8089"
    networks:
      isle-internal:

  telegraf:
    image: telegraf:latest
    # Telegraf requires network access to InfluxDB
    container_name: isle-telegraf-${CONTAINER_SHORT_ID}
    volumes:
      # Mount for telegraf configuration
      - ./config/tick/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - influxdb
    networks:
      isle-internal:
    #ports:
      # This port should be for rsyslog
    #  - "6514:6514"

  kapacitor:
    image: "kapacitor"
    container_name: isle-kapacitor-${CONTAINER_SHORT_ID}
    volumes:
      # Mount for kapacitor data directory
      - isle-kapacitor-data:/var/lib/kapacitor
      # Mount for kapacitor configuration
      - ./config/tick/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    # Kapacitor requires network access to Influxdb
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"
    networks:
      isle-internal:

  chronograf:
    image: chronograf:latest
    container_name: isle-chronograf-${CONTAINER_SHORT_ID}    
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      # Mount for chronograf database
      - isle-chronograf-data:/var/lib/chronograf/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
    networks:
      isle-internal:

# END TICK - Services

  traefik:
    image: traefik:1.7.9
    container_name: isle-proxy-${CONTAINER_SHORT_ID}
    networks:
      isle-internal:
      isle-external:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/proxy/acme.json:/acme.json      
      - ./config/proxy/traefik.toml:/etc/traefik/traefik.toml  ## Edit line 27, 28 with your cert and key names.
    labels:
      - traefik.port=8080
      - traefik.enable=true  ## NOT SAFE FOR PRODUCTION! ##
      - traefik.frontend.rule=Host:admin.${BASE_DOMAIN};


# Defined networks
networks:
  isle-internal:
  isle-external:

volumes:
  isle-db-data:
  isle-mysql-log:
  isle-solr-data:
  isle-apache-data:
  isle-portainer-data:
  isle-fedora-datastreamStore:
  isle-fedora-objectStore:
  isle-fedora-resourceIndex:
  isle-fedora-activemq:
  isle-fedora-XACML:
  isle-influxdb-data:
  isle-kapacitor-data:
  isle-chronograf-data: