version: 2
jobs:
  build:
    machine: true
    working_directory: ~/isle
    # branches:
    #   only:
    #     - travis
    parallelism: 1
    shell: /bin/bash --login
    steps:
      - checkout
      # - run:
      #     name: "Pull Submodules"
      #     command: |
      #       git submodule init
      #       git submodule update --remote

      # - run:
      #     name: Change main UID
      #     command: sed -i 's/ISLANDORA_UID=1000/ISLANDORA_UID=1001/g' .env
      - run:
          name: Fetch behat suite repo
          command: |
            mkdir data
            cd ~/isle
            git clone git@github.com:Born-Digital-US/isle-behat.git isle-behat

      - run: docker-compose up -d
      - run: sleep 40
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker exec -it isle-apache-ld bash /utility-scripts/isle_drupal_build_tools/isle_islandora_installer.sh
          no_output_timeout: 20m
      - run:
          name: Drush en dependencies
          command: |
            docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/all/modules/islandora && git clone https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories.git"
            docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_oralhistories"
            docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush dis overlay -y"
            sudo -- sh -c "echo 127.0.0.1 isle.localdomain >> /etc/hosts"
          no_output_timeout: 20m
          # REMOVED - we don't need these if we're not doing bulk ingest
          # docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_batch"
          # docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/all/modules/islandora && git clone https://github.com/mjordan/islandora_batch_with_derivs.git"
          # docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_batch_with_derivs"
          # docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_book_batch"
          # docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_newspaper_batch"
          # docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/all/modules/islandora && git clone https://github.com/MarcusBarnes/islandora_compound_batch.git"
          # docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -y -u 1 en islandora_compound_batch"

      - run:
          name: Set up for BEHAT on remote server
          command: |
            docker cp ~/isle/isle-behat isle-apache-ld:/var/www/html/sites/behat
            docker exec -it isle-apache-ld bash -c "chown -R islandora:www-data /var/www/html/sites/behat/"
            docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/behat && composer install "
            docker exec -it isle-apache-ld bash -c "chmod 700 /var/www/html/sites/behat/run-isle-tests.sh"
      # sudo chmod -R 777 ~/isle/data/isle-apache-data/sites/behat/
      # - run:
      #     name: Ingest base collection
      #     command: |
      #       docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -u 1 islandora_batch_with_derivs_preprocess --key_datastream=MODS --scan_target=/var/www/html/isle-behat/Batches-by-CModel/Collections/files --use_pids=true --namespace=samples --parent=islandora:root --content_models=islandora:collectionCModel"
      #       docker exec -it isle-apache-ld bash -c "cd /var/www/html && drush -u 1 islandora_batch_ingest"
      #     # no_output_timeout: 20m

  # test:
  #   machine: true
  #   working_directory: ~/isle
  #   parallelism: 1
  #   shell: /bin/bash --login
  #   parameters:
  #     full_ingest:
  #       type: boolean
  #       default: false
  #   steps:
      # - run: docker-compose up -d
      # - run: sleep 40
      - run:
          name: Run the behat tests
          command: |
            docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/behat && ./run-isle-tests.sh --run=services"
            docker exec -it isle-apache-ld bash -c "cd /var/www/html/sites/behat && ./run-isle-tests.sh --run=apache"
          no_output_timeout: 20m
      # - run:
      #     name: Move artifacts
      #     command: |
      #       docker cp isle-apache-ld:/var/www/html/sites/behat/results/ /tmp/artifacts
      #       docker cp isle-apache-ld:/var/www/html/sites/behat/debug/ /tmp/artifacts
      - run:
          name: Fix artifact file permissions
          command: |
            sudo -s
            mkdir /home/circleci/artifacts
            cp -r /home/circleci/isle/data/isle-apache-data/sites/behat/debug/* /home/circleci/artifacts/
            chown -R circleci:circleci /home/circleci/artifacts/
            exit
            exit
          when: always
      - store_artifacts:
          path: /home/circleci/artifacts/
          destination: behat-artifacts

# workflows:
#   version: 2
#   build-and-test: # sequentially
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
